- name: Update apt cache before installing packages
  apt:
    update_cache: yes
  become: yes  # Ensures command runs with sudo privileges

- name: Install required packages on GroupA
  apt:
    name: "{{ packages }}"
    state: present
  with_items: "{{ packages }}"
  become: yes  # Ensures package installation runs as sudo
  tags:
    - Install_A
  register: install_output

- name: Print success message
  when: install_output.changed  # Condition applied at the task level
  block:
    - name: Debug installation output
      debug:
        var: install_output

    - name: Print success message
      debug:
        msg: "Installation on A completed"
