- name: Install required packages on GroupA
  apt:
    name: "{{ packages }}"
    state: present
  with_items: "{{ packages }}"
  register: install_output
  tags:
    - install_groupA

- name: Debug installation output
  debug:
    msg: "{{ install_output }}"
  when: install_output.changed
  tags:
    - debug

- name: Notify handler to update cache
  command: apt update
  notify: update_apt_cache
