- name: Update apt cache before installing packages
  apt:
    update_cache: yes
  become: yes  # Ensures command runs with sudo privileges

- name: Install required packages on GroupA
  apt:
    name: "{{ packages }}"
    state: present
  with_items: "{{ packages }}"
  become: yes  # Ensures package installation runs as sudo

- name: Debug installation output
  debug:
    var: install_output
